### PR TITLE
Captcha Minigame

### PR DESCRIPTION
**Pull request by computer-kyle**
## Description

Adds a minigame that resembles a google captcha

## Type of Change

- [ ] Bug Fix
- [x] New Feature
- [x] Enhancement
- [ ] Refactor
- [ ] Documentation
- [ ] Other (please specify):

## Related Issue

N / A

## Changes Made

- Adds assets to one of the rooms on the west/left side of the map, which contains the new minigame
- Adds a new minigame canvas and script that resembles a google captcha
- The minigame features a random assortment of tiles representing ghosts or aliens, and the user is prompted to click the aliens
- The images contained in the tiles fade to another image when clicked
- The minigame can only be won by completing the captcha, which features a tile that needs to be clicked 6 times, all taking 5.6 seconds each

## Checklist

- [x] Code follows the project's coding style.
- [x] If asset(s) added, they have been made into a prefab
- [ ] Tests have been added/updated.
- [ ] Documentation has been updated (if applicable).
- [x] No unused code or assets remain.
- [x] Unity project builds without errors.

## Screenshots (if applicable)

image
image
image

## Additional Notes

The minigame is designed to be annoying to play :)

SampleScene will be reverted for an easy merge into main shortly

## Relevant UML Diagrams
image

### CODE REVIEW

**Review by brandon722 — APPROVED** [review]
## Pull Request Review
- **Functionality**:
  - Adds the captcha minigame on a panel screen.

- **Unused Code**: 
  - None

- **Code Style**: 
   - Properly following projects code style 

- **Script Structure**: 
   -  Script structure follows requirements of the project

- **Documentation**: 
   - Follows project documentation style

- **Build Integrity**: 
  - This PR works great! The captcha takes a while, which creates suspense for the player as they anticipate the ghost finding them. 

---

### Summary
This minigame is something everyone should be familiar with, and I like the images you used. I think the fade in and out effects take a really long time, and that can be polished up, but I like the length of the game overall due to the ghost needing time to find the player. Maybe we can speed up the fade in/out, but add more aliens that need to appear (more rounds to the captcha)? Other than that suggestion, everything works as intended. This is ready to merge.

**Review by krain0 — APPROVED** [review]
## Pull Request Review
- **Functionality**:
  - **New assets:** The new assets look great and help to make the map feel more complete
  - **Minigame:** The minigame works as intended, and is appropriately frustrating. I also enjoy the variety of pictures

- **Unused Code**:
  - None

- **Code Style**:
  - Matches our style

- **Script Structure**:
  - Everything is well organized

- **Documentation**:
  - Appropriate

- **Build Integrity**:
  - The game built without issue on my machine.

---

### Summary
The new assets look great. The minigame is a very cool idea, and I think it is a great addition. It is a bit time-consuming, but I think this accurately reflects how real captchas are, and making the player stay in one place for a while adds a nice challenge. The fade out time could probably be reduced a bit, but I think it is funny as is, and it is easy to change if we decide to, so I think it is ready to merge!

**Review by EricPettie — APPROVED** [review]
## Pull Request Review

- **Functionality:**  
  -  Adds captcha minigame 

- **Unused Code:**  
  -  None.

- **Code Style:**  
  - Aligns with the project.

- **Script Structure:**  
  - Everything is organized.

- **Documentation:**  
  - The comments are clear and describe the code well.

- **Build Integrity:**  
  - The game successfully built and ran.

---

### Summary
The minigame is a great idea, I also enjoy the assets you used. This is ready to merge.

**Comment by justinrreyes** [comment]
## Pull Request Review

- **Functionality:**  
  -  Adds captcha minigame 

- **Unused Code:**  
  -  None.

- **Code Style:**  
  - Aligns with the project.

- **Script Structure:**  
  - Everything is organized.

- **Documentation:**  
  - The comments are clear and describe the code well.

- **Build Integrity:**  
  - The game successfully built and ran.

---

### Summary
The minigame is a funny and fun idea, implemented well. Only thing I would say is that on my testing there was an infuriating time where an alien kept appearing for in the same square for about 5 times in a row. Maybe some code to ensure that the captcha does not last too long would make it more fun. Also decreasing the fade out time might be good as well.

**Review by justinrreyes — APPROVED** [review]
## Pull Request Review

- **Functionality:**  
  -  Adds captcha minigame 

- **Unused Code:**  
  -  None.

- **Code Style:**  
  - Aligns with the project.

- **Script Structure:**  
  - Everything is organized.

- **Documentation:**  
  - The comments are clear and describe the code well.

- **Build Integrity:**  
  - The game successfully built and ran.

---

### Summary
The minigame is a funny and fun idea, implemented well. Only thing I would say is that on my testing there was an infuriating time where an alien kept appearing for in the same square for about 5 times in a row. Maybe some code to ensure that the captcha does not last too long would make it more fun. Also decreasing the fade out time might be good as well.

**Pull request merged**
