### PR TITLE
Added to Title Screen: Options Menu, Key Event Management, and Sensitivity Settings

### PR DESCRIPTION
**Pull request by brandon722**
### Description
This pull request introduces several significant enhancements, including the addition of a functional options menu, key event management, and improved player sensitivity settings using `PlayerPrefs`. The purpose of these changes came from enhancing user experience by providing persistent and customizable sensitivity settings in the title screen.

### Type of Change
- [x] Bug Fix
- [x] New Feature
- [x] Enhancement
- [ ] Refactor
- [x] Documentation
- [ ] Other (please specify):

### Related Issue
Link to the issue this pull request addresses (if applicable):
- N/A

### Changes Made

**Main Canvas**:
- This is the primary canvas that holds all the UI features for the main title screen. The scripts are attached to this canvas.

**Options Canvas**:
- This canvas is initially inactive and is activated when the player presses "ESC" or selects the options menu from the main menu.
- It contains different panels for various settings. 

**Main Panel**:
- This panel is the default view when the options canvas is activated.
- It contains buttons for different settings categories (e.g., Sensitivity, Audio, Graphics). For now, we only have Sensitivity. 

**Sensitivity Panel**:
- This panel is shown when the player selects the "Sensitivity" button from the main panel.
- It contains sliders and input fields for adjusting pitch (Y) and yaw (X) sensitivity.
- It also includes "Apply", "Set to Default", and "Back" buttons.

**Back Button Functionality**:
- When the "Back" button on the sensitivity panel is pressed, it hides the sensitivity panel and shows the main panel.
- When the "Back" button on the main panel is pressed, it hides the entire options canvas.

- **Key Event Manager**:
  - Created a `KeyEventManager.cs` to handle key press events efficiently.
  - This component ensures robust detection of the ESC key press.

- **Sensitivity Settings**:
  - Changed the default sensitivity values in the `PlayerMovement.cs` script to 1.5f for both pitch and yaw.
  - Made the `PITCH_SENS, YAW_SENS` variables in `PlayerMovement.cs` public so they could be changed.
  - The `Start()` function of `PlayerMovement.cs` now loads previously saved sensitivities so that the option saves between runs.
  - Integrated sensitivity settings with the `OptionsMenuTitle.cs` script.
  - Added `PlayerPrefs` to persist sensitivity settings between scenes.
  - Implemented a feature to reset sensitivity settings to their defaults and automatically apply the changes.

### Checklist
- [x] Code follows the project's coding style.
- [x] If asset(s) added, they have been made into a prefab.
- [ ] Tests have been added/updated.
- [x] Documentation has been updated (if applicable).
- [x] No unused code or assets remain.
- [x] Unity project builds without errors.

### Screenshots (if applicable)
image
image
image

### Additional Notes
Any other information that would be helpful for the reviewer:
- Addressed a warning in `Interact.cs` where `FindObjectOfType` is depreciated. 
- There is a known bug with the Key Event Manager where if I tab out of Unity, then back in, it no longer detects the ESC key until you stop the player and start it again. I tried adding bug fixes but I am still in progress with those. This PR does not include my new `OnApplicationFocus` function until the bug fix has been implemented. I will create an issue after this PR gets approved. 
- I created a Prefab for the player and put it in the default project directory. I did not end up needing it, but it will still be useful to have later on. Feel free to remove if you find it creating clutter. 
- 
### Relevant UML Diagrams
image

### CODE REVIEW

**Review by uid106 — APPROVED** [review]
## Pull Request Review
- **Functionality**: 
  - Adds options to the title screen for adjusting sensitivity.

- **Event Trigger**: 
  - Options menu can be reached pressing the escape key.

- **Resizing Scripts**: 
  - The UI components in the inventory system display properly with my screen resolution
  
- **Unused Code**: 
  - No unused code blocks or unnecessary assets were found in the project.

- **Code Style**: 
  - The code adheres to the project's coding style and naming conventions.

- **Script Structure**: 
  - The files are well organized with title scripts in the "Title Assets" folder.

- **Documentation**: 
  - Changes are well documented.

- **Build Integrity**: 
  - The Unity project builds successfully without any errors, the title screen sensitivity functionality was working when tested.

---

### Summary

This change is functioning as intended, and allows x,y changes in sensitivity, this PR also fixes an issue in Interact.cs with a depreciated function being used that was throwing a soft warning.

**Review by computer-kyle — APPROVED** [review]
## Pull Request Review
- **Functionality**: 
  - The addition of the options menu works great. I was able to successfully navigate the menu and change the player camera sensitivity.

- **Resizing Scripts**: 
  - The options menu UI elements work well with 1920x1080 and larger display sizes.
  
- **Unused Code**: 
  - I was unable to find any unused code.

- **Code Style**: 
  - The code style aligns with the project well.

- **Script Structure**: 
  - The organization of scripts, the scene, and other elements like textures is great.

- **Documentation**: 
  -  The comments provided describe the code well.

- **Build Integrity**: 
  - The game builds and runs successfully.

---

### Summary

The addition of the options menu is a great feature and functions well. It is ready to merge into the main branch.

**Comment by computer-kyle** [comment]
Despite this PR being approved, lets hold off on merging it until #20 can be merged first. From there, we will look for any merge conflicts or issues with that branch.

**Review by krain0 — APPROVED** [review]
## Pull Request Review
- **Functionality**: 
  - I am able to navigate the settings menu and adjust all available settings. 

- **Resizing Scripts**: 
  - The UI appears at an appropriate size on my display.
  
- **Unused Code**: 
  - None

- **Code Style**: 
  - Aligns with our conventions.

- **Script Structure**: 
  -  Everything is reasonably laid out. 

- **Documentation**: 
  -  Comments clearly describe the purpose of the code

- **Build Integrity**: 
  - Everything built and ran correctly on my machine.

---

### Summary
The options menu works great and looks nice. I didn't have any problems interacting with it. I also tried merging it with the main branch locally and this PR doesn't appear to mess with prior functionality. Looks good to merge!

**Pull request merged**
