### PR TITLE
Adding doors

### PR DESCRIPTION
**Pull request by krain0**
## Description

Added doors that the player and antagonist can interact with. 

## Type of Change

- [ ] Bug Fix
- [x] New Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] Documentation
- [ ] Other (please specify):

## Related Issue
None

## Changes Made

- Door prefab has a door frame and a door. Opening and closing the door is managed with animations and an animator controller. 
- DoorController.cs provides an interface for changing and inspecting the door's state. 
- Doors prefab. This is just a collection of Door prefabs placed across the map. To avoid changing the scene file, I didn't put this in the scene. 
- DoorInteractionManual.cs was added to the player. This allows the player to click to open doors if it is within range.
- DoorInteractionAutomatic.cs was added to the antagonist, and this just constantly tries to open any door that is in range. 

## Checklist
- [X] Code follows the project's coding style.
- [X] If asset(s) added, they have been made into a prefab
- [ ] Tests have been added/updated.
- [X] Documentation has been updated (if applicable).
- [X] No unused code or assets remain.
- [X] Unity project builds without errors.

## Screenshots (if applicable)
[Video link](https://cdn.discordapp.com/attachments/1277835834292441149/1297390698693398669/Screen_Recording_2024-10-19_at_7.33.38_PM.mp4?ex=671a5dfe&is=67190c7e&hm=e2c1bdb7e98a05fb1f55608067c57969ce9cd3c8384d569ed62fe96b22896315&)
## Additional Notes

The textures on this prefab aren't intended to be final.

If you want to test my changes, just drag the Doors prefab into the hierarchy, and it should place them correctly. You also need to drag DoorInteractionManual.cs to the Player, and DoorInteractionAutomatic.cs to the antagonist.

I also added .DS_Store to the .gitignore, these are files that mac's automatically create. 

## Relevant UML Diagrams
image

### CODE REVIEW

**Comment by caseycodes32** [comment]
Hey, excellent job adding interactable doors!

I tried out your PR and it worked flawlessly. The doors are implemented as prefabs, so they're also entirely modular and can be added or removed without consequence. I think that this addition added a lot to the game.

I could not find any issues, and I'd say this is ready to merge into main!

**Review by computer-kyle — APPROVED** [review]
Hey, excellent job adding interactable doors!

I tried out your PR and it worked flawlessly. The doors are implemented as prefabs, so they're also entirely modular and can be added or removed without consequence. I think that this addition added a lot to the game.

I could not find any issues, and I'd say this is ready to merge into main!

**Comment by brandon722** [comment]
The doors look great! I had no issues using the doors and the animations and controller for door interactions work fine. The code looks clean, and no errors appear in the console when running your changes.

Overall, I also found no issues and am confident that this is ready to be merged.

**Review by brandon722 — APPROVED** [review]

**Comment by uid106** [comment]
Double checked that the doors functioned as intended, double checked and they were functioning. One suggestion would be placing them around the map, but this will likely be implemented in the future when map objectives are created, so at this moment this PR looks ready to merge, and I will merge it.

**Pull request merged**
