### PR TITLE
week2_antagonist_creation

### PR DESCRIPTION
**Pull request by uid106**
## Description

Creates an antagonist model that can move towards the players position and creates a stopping distance variable and speed variable to keep antagonist from infinitely moving through the player. 

## Type of Change

- [ ] Bug Fix
- [x] New Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] Documentation
- [ ] Other (please specify):

## Related Issue

Link to the issue this pull request addresses (if applicable):
- No related issue.

## Changes Made

- Moves antagonist towards player at defined speed.
- Checks for player position to move towards player.
- Creates a stopping distance which keeps the character from bouncing through the player and never stopping.
- Set up antagonist object in object tree with default texture which will need to be changed later.

## Checklist

- [x] Code follows the project's coding style.
- [x] If asset(s) added, they have been made into a prefab
- [ ] Tests have been added/updated.
- [x] Documentation has been updated (if applicable).
- [x] No unused code or assets remain.
- [x] Unity project builds without errors.

## Screenshots (if applicable)

image

## Additional Notes

N/A

### CODE REVIEW

**Comment by computer-kyle** [comment]
This is a great first implementation of the antagonist with simple movement. I ran your code and did find one line of code that could be improved:

In the file **AntagonistController.cs:**
`rb.AddForce(direction * speed);`

This line of code should probably account for framerate delta-time, as it will impact the antagonist's movement differently based on the framerate/performance of anyone running the game. Originally, and likely because my machine is running the game at a different framerate than yours, the antagonist movement did not work as intended. I changed the line to the following: 

`rb.AddForce(direction * speed * Time.deltaTime * 400);`

This seemed to work for me. The number 400 is kind of ambiguous, but it's basically a correction value for the very small delta time value.

**Comment by uid106** [comment]
> This is a great first implementation of the antagonist with simple movement. I ran your code and did find one line of code that could be improved:
> 
> In the file **AntagonistController.cs:** `rb.AddForce(direction * speed);`
> 
> This line of code should probably account for framerate delta-time, as it will impact the antagonist's movement differently based on the framerate/performance of anyone running the game. Originally, and likely because my machine is running the game at a different framerate than yours, the antagonist movement did not work as intended. I changed the line to the following:
> 
> `rb.AddForce(direction * speed * Time.deltaTime * 400);`
> 
> This seemed to work for me. The number 400 is kind of ambiguous, but it's basically a correction value for the very small delta time value.

Added this change to rb.AddForce and pushed commit, tested on my machine and is still working as intended.

**Comment by uid106** [comment]
Minor update to HealthSlider that's also included in healthbar pull request. Merging pull request.

**Review by brandon722 — COMMENTED** [review]
This was a really good starting point for the antagonist implementation. The script includes a stopping distance variable and a speed variable to prevent the antagonist from moving through the player indefinitely. The code is cleanly organized, the assets have been made into prefabs, and there is no dead code with this. 

As of now, the capsule does not stay upright and it rolls around while it chases the player. This is not an issue now, but we will have to see how this behaves once we upload the textures of the model. This is ready to merge.

**Pull request merged**
